name: CI Tests

on:
  push:
  pull_requests:

jobs:
  job-name-test-ci:
    runs-on: ubuntu-20.04
  
  strategy:
    matrix:
      # Testar duas versões do node
      node-version: [14.x, 16.x]

  # Etapas da ação
  steps:
  # Checkout do código
  - uses: actions/checkout@v2
  # Configurar a matrix
  - name: Use Node.js ${{ matrix.node-version }}
  uses: actions/setup-node@v2
  with:
    node-version: ${{ matrix.node-version }}

  # parecido com o npm install, mas não altera o package.json ou package-lock.json
  - run: npm ci

  # Roda os testes
  - run: npm run test